key_id: {{ env['AWS_KMS_KEY'] }}
cipher_texts:
  conf: AQECAHgvsm3WJp0dJXqBkWr+9ODl78mLm+xVX74sayaR4z5yTgAAARswggEXBgkqhkiG9w0BBwagggEIMIIBBAIBADCB/gYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAxcU6ekSyb10CYsmn0CARCAgdAF2Jscwt4sKlZ/R7f9ZSLJVltt0c0hBTSJV50B08q0w0gN0xMdnJeg7RPE85PVINqp9W2tdDWDKsLZ1DW1wGkPe7t3Jp30Y5FXWkwZgM0DkWa10aYWmZlmlfEm9cs8g/7AO9xpMo3CqeFOFCwPnfz2n6cKo2z7Cml8d0m6DGpvpz2U9w0y2hGKdMtsMIQwHfVcd4xuinmCTVUt+15bkZB2vUrydPU//I53mjy0OGcExBnz0EvftYEYtYr9MjIbRCqe6DQQsWkxLjtK7yKf49Vu
secret_files: {}
