profile: default
region: us-west-2
versioning: false
default_alias: null
clean_build: false
configuration:
  name: lambda_email2phone
  runtime: python2.7
  role: {{ env['AWS_LAMBDA_ROLE'] }}
  handler: email2phone.lambda_handler
  description: email to phone via aws lambda
  timeout: 10
  memory_size: 128
